CREATE TABLE IF NOT EXISTS ADMIN(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  NAME VARCHAR(20) NOT NULL,
  USERNAME VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(68) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;