CREATE TABLE IF NOT  EXISTS `USER` (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  USERNAME VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(68) NOT NULL,
  CREATED_BY INT NOT NULL,
  FOREIGN KEY (CREATED_BY) REFERENCES CLIENT(ID)
);