CREATE TABLE IF NOT EXISTS REGION(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  COUNTRY VARCHAR(100) NOT NULL
);

# CREATE TABLE IF NOT EXISTS PRODUCT_LANGUAGE_MODULE(
#   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
#   LANGUAGE_ID INT NOT NULL,
#   MODULE_ID INT NOT NULL,
#   PRODUCT_ID INT NOT NULL,
#   FOREIGN KEY (LANGUAGE_ID) REFERENCES `LANGUAGE`(ID),
#   FOREIGN KEY (MODULE_ID) REFERENCES `MODULE`(ID),
#   FOREIGN KEY (PRODUCT_ID) REFERENCES `PRODUCT`(ID)
# );

