
CREATE TABLE IF NOT EXISTS LANGUAGE_MODULE(
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MODULE_ID INT NOT NULL,
  LANGUAGE_ID INT NOT NULL,
  FOREIGN KEY (MODULE_ID) REFERENCES MODULE(ID),
  FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE(ID)
);
