CREATE TABLE IF NOT EXISTS PLAN(
 ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 DESCRIPTION VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PLAN_PRODUCT(
  PLAN_ID INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  FOREIGN KEY(PLAN_ID) REFERENCES PLAN(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID),
  PRIMARY KEY(PLAN_ID, PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS SUBSCRIPTION(
 ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 USER_ID INT NOT NULL,
 PLAN_ID INT NOT NULL,
 START DATE NOT NULL,
 `END` DATE NOT NULL,
 REGION_ID INT NOT NULL,
 FOREIGN KEY(USER_ID) REFERENCES USER(ID),
 FOREIGN KEY (PLAN_ID) REFERENCES PLAN(ID),
 FOREIGN KEY (REGION_ID) REFERENCES REGION(ID)
);