-- CREATE ADMIN
INSERT INTO ADMIN(NAME, USERNAME, PASSWORD) VALUES ('santhosh', 'bonala', 'password');

-- CREATE CLIENTS
INSERT INTO CLIENT(NAME, USERNAME, PASSWORD) VALUES ('client1', 'client1', 'password');
INSERT INTO CLIENT(NAME, USERNAME, PASSWORD) VALUES ('client2', 'client2', 'password');

-- CREATE USERS
INSERT INTO USER(NAME, USERNAME, PASSWORD, CREATED_BY) VALUES ('user1', 'user1', 'password', 1);
INSERT INTO USER(NAME, USERNAME, PASSWORD, CREATED_BY) VALUES ('user2', 'user2', 'password', 2);
INSERT INTO USER(NAME, USERNAME, PASSWORD, CREATED_BY) VALUES ('user3', 'user3', 'password', 1);
INSERT INTO USER(NAME, USERNAME, PASSWORD, CREATED_BY) VALUES ('user4', 'user4', 'password', 2);
INSERT INTO USER(NAME, USERNAME, PASSWORD, CREATED_BY) VALUES ('user5', 'user5', 'password', 1);

-- CREATE PRODUCTS
INSERT INTO PRODUCT(NAME, DESCRIPTION) VALUES('product1', 'product1');
INSERT INTO PRODUCT(NAME, DESCRIPTION) VALUES('product2', 'product2');
INSERT INTO PRODUCT(NAME, DESCRIPTION) VALUES('product3', 'product3');

-- ADD MODULES
INSERT INTO `MODULE`(`MODULE`, PRODUCT_ID) VALUES('PART A', 1);
INSERT INTO `MODULE`(`MODULE`, PRODUCT_ID) VALUES('PART B', 1);
INSERT INTO `MODULE`(`MODULE`, PRODUCT_ID) VALUES('PART C', 1);
INSERT INTO `MODULE`(`MODULE`, PRODUCT_ID) VALUES('PART AA', 2);
INSERT INTO `MODULE`(`MODULE`, PRODUCT_ID) VALUES('PART BB', 2);

-- ADD LANGUAGES
INSERT INTO `LANGUAGE`(`LANGUAGE`) VALUES('English');
INSERT INTO `LANGUAGE`(`LANGUAGE`) VALUES('Telugu');

-- ADD LANGUAGE_MODULE RELATIONSHIP
INSERT INTO LANGUAGE_MODULE(LANGUAGE_ID, MODULE_ID) VALUES(1, 1);
INSERT INTO LANGUAGE_MODULE(LANGUAGE_ID, MODULE_ID) VALUES(1, 2);
INSERT INTO LANGUAGE_MODULE(LANGUAGE_ID, MODULE_ID) VALUES(1, 3);
INSERT INTO LANGUAGE_MODULE(LANGUAGE_ID, MODULE_ID) VALUES(1, 4);
INSERT INTO LANGUAGE_MODULE(LANGUAGE_ID, MODULE_ID) VALUES(2, 5);
INSERT INTO LANGUAGE_MODULE(LANGUAGE_ID, MODULE_ID) VALUES(2, 1);
INSERT INTO LANGUAGE_MODULE(LANGUAGE_ID, MODULE_ID) VALUES(2, 2);



-- ADD REGIONS
INSERT INTO REGION(COUNTRY) VALUES('INDIA');
INSERT INTO REGION(COUNTRY) VALUES('UNITED STATES');
INSERT INTO REGION(COUNTRY) VALUES('CANADA');

-- ADD PLAN
INSERT INTO PLAN(DESCRIPTION) VALUES('PLAN 1');
INSERT INTO PLAN(DESCRIPTION) VALUES('PLAN 2');
INSERT INTO PLAN(DESCRIPTION) VALUES('PLAN 3');
INSERT INTO PLAN(DESCRIPTION) VALUES('PLAN 4');

-- ADD PLAN_PRODUCT_LANGUAGE_MODULE
INSERT INTO PLAN_PRODUCT VALUES(1, 1);
INSERT INTO PLAN_PRODUCT VALUES(1, 2);
INSERT INTO PLAN_PRODUCT VALUES(1, 3);
INSERT INTO PLAN_PRODUCT VALUES(2, 3);
INSERT INTO PLAN_PRODUCT VALUES(2, 2);
INSERT INTO PLAN_PRODUCT VALUES(3, 1);
INSERT INTO PLAN_PRODUCT VALUES(3, 3);

-- CREATE SUBSCRIPTIONS
INSERT INTO SUBSCRIPTION(USER_ID, PLAN_ID, `START`, `END`, REGION_ID) VALUES(1, 1, '2019-02-10', '2019-02-20', 1);
INSERT INTO SUBSCRIPTION(USER_ID, PLAN_ID, `START`, `END`, REGION_ID) VALUES(1, 2, '2019-02-05', '2019-02-25', 1);
INSERT INTO SUBSCRIPTION(USER_ID, PLAN_ID, `START`, `END`, REGION_ID) VALUES(2, 1, '2019-02-09', '2019-03-20', 2);
INSERT INTO SUBSCRIPTION(USER_ID, PLAN_ID, `START`, `END`, REGION_ID) VALUES(3, 2, '2019-01-10', '2019-05-15', 1);
